### ISSUE TITLE
Error: "E481: No range allowed" when calling Oscyank

### ISSUE THREAD

**Issue by mattsawyer77** [greymd/oscyank.vim#1]
Thanks for writing this plugin, as it purports to be exactly what I've been looking for! However, it isn't working for me. My local machine is a Mac, where I'm using iTerm2 to ssh to my arch linux machine, where I'm running tmux 2.5 and neovim 0.2.0. Perhaps the problem is with neovim?

**Comment by greymd** [comment]
@mattsawyer77 

Hi, thank you for trying this plugin.
At first, this plugin had not supported range selection feature before.
But I have also thought that it's helpful.

Changes to support the range selection yank were pushed to master.
Can you try it?  As for the usage, refer to [Readme.md#usage](https://github.com/greymd/oscyank.vim#usage).

Thanks
