### ISSUE TITLE
Works in Vim but not in NeoVim

### ISSUE THREAD

**Issue by ratheesh** [greymd/oscyank.vim#4]
This plugin is very nice and works fine with `vim`, but unfortunately, this does not work in `neovim`
Can you please confirm if there an issue with neovim? issue #1 does not conclude on this.

**Comment by greymd** [comment]
Hi, thank you for using this plugin.
it may take much time to fix it, because I do not use `neovim` basically. 
Stay tuned.

FYI: there is very similar plugin: https://github.com/haya14busa/vim-poweryank
it is worth trying it out.

**Comment by ratheesh** [comment]
Looks like this is a neovim issue. Even vim-poweryank does not work with nvim. I will try to reach out to nvim people. Thanks for the support.
