### ISSUE TITLE
Does it work on windows with xshell/putty tty emulator?

### ISSUE THREAD

**Issue by andoryu-** [greymd/oscyank.vim#5]
Hi,
Just found this amazing repo, but it dosn't seem to work under my environment(win10+xshell).
Does it suppose to work on windows with tty emulator?

**Comment by greymd** [comment]
Hi,
Sorry, it may not support to work on windows with tty emulator.
I've never tested it on the windows environment.

FYI: there is very similar plugin: https://github.com/haya14busa/vim-poweryank
it is worth trying it out :)
